"""
A smolagent for deep-research tasks.

Uses a two-agent architecture:
  1. Planner: a lightweight agent (no tools) that reasons about the
     research question and produces a step-by-step research plan.
  2. Executor: a separate agent with search/fetch/report tools that
     executes the plan.

Usage:
    python agent-deep.py "What are the latest advances in photonic computing? Generate a concise report with key findings and URLs."
    python agent-deep.py --backend deepseek "Compare retrieval-augmented generation vs long-context models"
    python agent-deep.py --no-plan "Create a report on the current state of quantum machine learning, skipping the planning step and going straight to execution."
    python agent-deep.py --max-steps 25 "How is CRISPR being used in agricultural biotechnology? Create a report with citations."
    python agent-deep.py --skill research "Summarise the latest advances in photonic computing."  # Load research skill
"""

import argparse
import asyncio
import contextlib
import sys
import warnings

from tools import (
    fetch_webpage,
    generate_research_report,
    read_memory,
    update_memory,
    web_search,
)
from utils import (
    approve_plan,
    load_memory_for_task,
    make_code_agent,
    make_planner_agent,
    save_session_trace,
    setup_environment,
)

DEEP_RESEARCH_TOOLS = [
    web_search,
    fetch_webpage,
    generate_research_report,
    read_memory,
    update_memory,
]

DEEP_RESEARCH_IMPORTS = [
    "requests",
    "bs4",
    "ddgs",
    "markdownify",
    "json",
    "re",
    "datetime",
    "pathlib",
]

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="A smolagents deep-research agent.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "prompt",
        nargs="?",
        default=(
            "Research the topic 'recent advances in small language models "
            "(SLMs) under 3B parameters'.  Search the web for the latest "
            "information, fetch and read the most promising pages, then "
            "produce a concise, well-structured summary with key findings "
            "and citations (URLs)."
        ),
        help="The research question or topic for the agent to investigate.",
    )
    parser.add_argument(
        "--backend",
        choices=["openai", "deepseek"],
        default="openai",
        help="LLM backend to use (default: %(default)s).",
    )
    parser.add_argument(
        "--no-plan",
        action="store_true",
        help="Skip the planner agent entirely (run executor directly with the task).",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=20,
        help="Maximum number of steps the executor agent may take (default: %(default)s).",
    )
    parser.add_argument(
        "--skill",
        type=str,
        default=None,
        help="Name of a skill to load from skills/<name>/SKILL.md (e.g. 'research').",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=120,
        help="Max seconds per tool execution step (default: 120, smolagents default: 30). "
        "Use 0 or negative to disable.",
    )
    args = parser.parse_args()

    # Load environment
    env = setup_environment()

    # Phase 1: Planning (separate agent instance, no tools)
    if not args.no_plan:
        planner = make_planner_agent(
            env=env,
            backend=args.backend,
            max_steps=5,
            skill=args.skill,
        )

        plan_prompt = (
            f"You are a planning agent. Your ONLY job is to create a detailed, "
            f"step-by-step research plan for the following question. Do NOT "
            f"execute anything — just think and write the plan. Include specific "
            f"search queries and a strategy for cross-referencing sources.\n\n"
            f"## Research Question\n\n{args.prompt}"
        )
        plan_result = planner.run(plan_prompt)
        plan = plan_result if isinstance(plan_result, str) else plan_result.output

        # Show the plan and ask the user to approve it
        approve_plan(plan)

        # Save planner trace
        save_session_trace(
            agent=planner,
            task=plan_prompt,
            backend=args.backend,
            state="success",
            output=plan,
        )

        # Build the full task for the executor: plan + original question
        task_for_executor = (
            f"## Research Plan (generated by Planner agent)\n\n"
            f"{plan}\n\n"
            f"---\n\n"
            f"## Research Question\n\n"
            f"{args.prompt}\n\n"
            f"Follow the plan above to research this question thoroughly."
        )
    else:
        task_for_executor = args.prompt
        print("⚡ Planning skipped — running executor directly.\n")

    # Phase 2: Execution (separate agent instance, with all tools)
    runner = make_code_agent(
        env=env,
        backend=args.backend,
        max_steps=args.max_steps,
        tools=DEEP_RESEARCH_TOOLS,
        additional_authorized_imports=DEEP_RESEARCH_IMPORTS,
        skill=args.skill,
        executor_timeout=args.timeout if args.timeout > 0 else None,
    )

    # Run the executor agent on the task (with plan embedded if planner was used)
    try:
        task_with_memory = load_memory_for_task(task_for_executor)
        run_result = runner.run(task_with_memory, return_full_result=True)
        print(f"\n🎉 Research complete:\n{run_result.output}")

        # Save the full session trace to traces/
        save_session_trace(
            agent=runner,
            task=args.prompt,
            backend=args.backend,
            state=run_result.state,
            output=run_result.output,
        )
    except Exception as e:
        if "interrupted" in str(e).lower():
            print("\n🛑 Agent was interrupted by user.")
            # Try to save a partial trace with whatever steps were taken
            with contextlib.suppress(Exception):
                save_session_trace(
                    agent=runner,
                    task=args.prompt,
                    backend=args.backend,
                    state="interrupted",
                    output="[interrupted]",
                )
            sys.exit(0)
        raise
    finally:
        # Clean up asyncio event loop to avoid ResourceWarning
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", ResourceWarning)
            try:
                loop = asyncio.get_event_loop()
                if not loop.is_closed():
                    loop.close()
            except Exception:
                pass
