"""
A smolagents agent for sales forecasting.

Uses a two-agent architecture:
  1. Planner: a lightweight agent (no tools) that reasons about the task
     and produces a step-by-step plan.
  2. Executor: a separate agent with the full tool set that executes the plan.

Usage:
    python agent-forecast.py                           # Uses OpenAI by default with the built-in prompt
    python agent-forecast.py --backend deepseek        # Use DeepSeek instead
    python agent-forecast.py --no-plan                 # Skip the planner, run executor directly
    python agent-forecast.py --max-steps 30            # Allow more executor steps
    python agent-forecast.py --skill forecast          # Load the forecast skill instructions
"""

import argparse
import contextlib
import sys

from tools import (
    create_forecast_plot,
    download_dataset_from_hub,
    forecast_next_7_days,
    generate_final_report,
    preprocess_time_series_data,
    read_memory,
    train_xgboost_forecaster,
    update_memory,
)
from utils import (
    approve_plan,
    load_memory_for_task,
    make_code_agent,
    make_planner_agent,
    save_session_trace,
    setup_environment,
)

FORECAST_TOOLS = [
    download_dataset_from_hub,
    preprocess_time_series_data,
    train_xgboost_forecaster,
    forecast_next_7_days,
    create_forecast_plot,
    generate_final_report,
    read_memory,
    update_memory,
]

FORECAST_IMPORTS = [
    "datasets",
    "pandas",
    "numpy",
    "pickle",
    "os",
    "shutil",
    "datetime",
]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="A smolagents sales forecast agent.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "prompt",
        nargs="?",
        default="Download the dataset 'AiresPucrs/time-series-data' from the "
        "Hugging Face Hub, preprocess it, train an XGBoost forecaster, "
        "predict the next 7 days of sales, create a plot, and generate "
        "a final report folder with all artifacts.",
        help="The task for the agent to perform.",
    )
    parser.add_argument(
        "--backend",
        choices=["openai", "deepseek"],
        default="openai",
        help="LLM backend to use (default: %(default)s).",
    )
    parser.add_argument(
        "--no-plan",
        action="store_true",
        help="Skip the planner agent entirely (run executor directly with the task).",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=15,
        help="Maximum number of steps the executor agent may take (default: %(default)s).",
    )
    parser.add_argument(
        "--skill",
        type=str,
        default=None,
        help="Name of a skill to load from skills/<name>/SKILL.md (e.g. 'forecast').",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=120,
        help="Max seconds per tool execution step (default: 120, smolagents default: 30). "
        "Use 0 or negative to disable.",
    )
    args = parser.parse_args()

    # Load environment
    env = setup_environment()

    # Phase 1: Planning (separate agent instance, no tools)
    if not args.no_plan:
        planner = make_planner_agent(
            env=env,
            backend=args.backend,
            max_steps=5,
            skill=args.skill,
        )

        plan_prompt = (
            f"You are a planning agent. Your ONLY job is to create a detailed, "
            f"step-by-step plan for the following task. Do NOT execute anything — "
            f"just think and write the plan.\n\n"
            f"## Task\n\n{args.prompt}"
        )
        plan_result = planner.run(plan_prompt)
        plan = plan_result if isinstance(plan_result, str) else plan_result.output

        # Show the plan and ask the user to approve it
        approve_plan(plan)

        # Save planner trace
        save_session_trace(
            agent=planner,
            task=plan_prompt,
            backend=args.backend,
            state="success",
            output=plan,
        )

        # Build the full task for the executor: plan + original task
        task_for_executor = (
            f"## Plan (generated by Planner agent)\n\n"
            f"{plan}\n\n"
            f"---\n\n"
            f"## Task\n\n"
            f"{args.prompt}\n\n"
            f"Follow the plan above to complete this task."
        )
    else:
        task_for_executor = args.prompt
        print("⚡ Planning skipped — running executor directly.\n")

    # Phase 2: Execution (separate agent instance, with all tools)
    runner = make_code_agent(
        env=env,
        backend=args.backend,
        max_steps=args.max_steps,
        tools=FORECAST_TOOLS,
        additional_authorized_imports=FORECAST_IMPORTS,
        skill=args.skill,
        executor_timeout=args.timeout if args.timeout > 0 else None,
    )

    # Run the executor agent on the task (with plan embedded if planner was used)
    try:
        # Always inject persistent memory into the task before running
        task_with_memory = load_memory_for_task(task_for_executor)
        run_result = runner.run(task_with_memory, return_full_result=True)
        print(f"\n🎉 Agent result: {run_result.output}")

        # Save the full session trace to traces/
        save_session_trace(
            agent=runner,
            task=args.prompt,
            backend=args.backend,
            state=run_result.state,
            output=run_result.output,
        )
    except Exception as e:
        if "interrupted" in str(e).lower():
            print("\n🛑 Agent was interrupted by user.")
            # Try to save a partial trace with whatever steps were taken
            with contextlib.suppress(Exception):
                save_session_trace(
                    agent=runner,
                    task=args.prompt,
                    backend=args.backend,
                    state="interrupted",
                    output="[interrupted]",
                )
            sys.exit(0)
        raise
